### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by xvixvi** [r1cu/ebuntris#2]
:date: 19.02.
:hourglass: 20:00

<h2>Yleisesti koodista ja projektista</h2>

- Koodi on hyvin sisennettyä ja selkeää lukea.
- Luokat ovat ehyitä kokonaisuuksia, ja luokkajako on looginen
- Jako pakkauksiin on selkeä. Enum -luokat olisi ehkä voinut eriyttää logiikasta omaksi pakkauksekseen selkeyden vuoksi.
- Ohjelma vaikuttaa toimivalta. Olisiko tilaisuus lisätä ominaisuuksia, esimerkiksi alkuvalikko ja vaikeustaso, tai mahdollisesti uusi pelimuoto?
- Testien rivikattavuus vaikuttaa hyvältä. Onko testaus kuitenkin kattavaa kaikkein kriittisimmillä osa-alueilla, esim logiikassa?
- Pitäisikö pelin ohjeet laittaa jonnekin, vaikka kyseessä onkin hyvin intuitiivinen peli?

### Kaatumisongelma

Hetken aikaa koodia tarkasteltuani päätin ajaa ohjelman, joka vaikutti valmiilta ja helposti pelattavalta. Rivit katosivat odotetusti ja palikat liikkuivat vaivattomasti. Kuitenkin hetken pelattuani päädyin tilanteeseen, jossa tuhosin useamman kuin yhden rivin kerralla, ja yllätyksekseni ohjelma kaatui tuottaen seuraavan virheilmoituksen (tähän kopioitu vain ilmoituksen alku):

`Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at hanninen.riku.ebuntris.logiikka.Palikka.kaanny(Palikka.java:193)
	at hanninen.riku.ebuntris.logiikka.Pelialusta.voiKaantya(Pelialusta.java:68)
	at hanninen.riku.ebuntris.gui.Nappaimistonkuuntelija.keyPressed(Nappaimistonkuuntelija.java:42) `

Ongelma lienee helposti korjattavissa, kunhan asiaan perehtyy tarkemmin.

**Comment by r1cu** [comment]
Moi ja kiitos kommenteista! 

Juuri tosiaan pushasin päivän hommat githubiin joten valitettavasti taisit katselmoida ns. vanhaa versiota, mutta eipä se haittane.

Kaatumisongelmaa ei pitäisi enää olla, sekä alustavaa päävalikkoa on luotu ja pelimuotoja on tarkoitus lisätä vielä kurssin puitteissa nykyisen maratoonin lisäksi. Ja mitä tuohon testauksen kattavuuteen tulee niin taidat olla oikeassa :).
